### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by queerviolet** [Dysfunctional-programmers/onerica#1]
```sh
$ npm run build-client
```

Output:
```
Hash: d5e1e95f94cde678290d
Version: webpack 2.7.0
Time: 55ms

ERROR in Entry module not found: Error: Can't resolve './client/index.jsx' in '/Users/ashi/fs/onerica'
```

**Comment by queerviolet** [comment]
This was me at 5d33f5c, sorry.

**Comment by queerviolet** [comment]
@glebec Yeah, fixed.

**Comment by glebec** [comment]
```sh
npm build
```

@queerviolet this doesn't seem to do anything, but I presume you mean `npm run build-client`.

...

Ah yes, that does fail.

**Comment by queerviolet** [comment]
@glebec Sorry, fixed that too.

**Comment by glebec** [comment]
AH, I see the problem at [this line](https://github.com/Dysfunctional-programmers/onerica/blob/5d33f5ca770e5cbccaf9e3c291ec8a04fecc2def/webpack.config.js#L5).
